server:
  port: 8080
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  application:
    name: ssm-demo-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456

---
shiro:
  unauthorizedUrl: /unauthorizedurl       # 访问未获授权的页面时，默认的跳转路径
  web:
    enabled: true                         # 开启 shiro
  loginUrl: /login                        # 登录页面
  successUrl: /index                      # 登录成功的跳转页面
  sessionManager:
    sessionIdCookieEnabled: true          # 是否允许将sessionId 放到 cookie 中
    sessionIdUrlRewritingEnabled: true    # 是否允许将 sessionId 放到 Url 地址拦中

