server:
  port: 9090

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

spring:
  application:
    name: spring-boot-oauth2-client
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456

logging:
  level:
    com:
      steven:
        shiro: DEBUG

authorizeUrl: https://api.weibo.com/oauth2/authorize
accessTokenUrl: https://api.weibo.com/oauth2/access_token
clientId: 2002214738
clientSecret: 1c183be503847bf86ce3c033ce7ab05d
redirectUrl: http://127.0.0.1:8080/getResourcesFromWeibo
response_type: code
userInfoUrl: /oauth-client/getUserInfo