server:
  port: 9090

mybatis:
  mapperLocations: classpath*:/mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-not-delete-value: N
      logic-delete-value: Y
      logic-delete-field: deleted

spring:
  datasource:
    url: jdbc:mysql://10.10.10.138:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 666666
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    property-naming-strategy: LOWER_CAMEL_CASE